#!/usr/bin/env bash
set -euo pipefail

# ── Stella Setup Wizard ──────────────────────────────────────────
# Produces a ready-to-run stella.toml and docker-compose.yml.
# Idempotent: re-run any time to change settings.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/stella-data/config"
CONFIG_FILE="$CONFIG_DIR/stella.toml"
TPL_DIR="$CONFIG_DIR/tpl"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"

# ── Helpers ──────────────────────────────────────────────────────

prompt() {
  local var="$1" label="$2" default="$3" secret="${4:-false}"
  local display_default="$default"
  if [[ "$secret" == "true" && -n "$default" ]]; then
    display_default="********"
  fi

  if [[ -n "$display_default" ]]; then
    label="$label [$display_default]"
  fi

  local value
  if [[ "$secret" == "true" ]]; then
    read -rsp "  $label: " value
    echo
  else
    read -rp "  $label: " value
  fi

  if [[ -z "$value" ]]; then
    value="$default"
  fi
  eval "$var=\"\$value\""
}

# Read a value from existing stella.toml (best-effort).
toml_get() {
  local key="$1"
  if [[ -f "$CONFIG_FILE" ]]; then
    # Match: key = "value" or key = 'value' or key = value
    sed -n "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*\"\{0,1\}\([^\"]*\)\"\{0,1\}[[:space:]]*$/\1/p" "$CONFIG_FILE" | tail -1
  fi
}

# ── Banner ───────────────────────────────────────────────────────

echo ""
echo "Welcome to Stella Setup!"
echo ""

# ── Load existing defaults ───────────────────────────────────────

cur_openai_key="$(toml_get openai_api_key)"
cur_gemini_key="$(toml_get gemini_api_key)"
cur_realtime_backend="$(toml_get realtime_backend)"
cur_google_email="$(toml_get google_email)"
cur_google_password="$(toml_get google_password)"
cur_totp_secret="$(toml_get totp_secret)"
cur_rag_api_key="$(toml_get api_key)"
cur_db_password="$(toml_get password)"

# ── 1. Realtime Backend & API Keys ──────────────────────────────

echo "1. Stella supports OpenAI Realtime and Gemini Live for voice."
echo "   Choose your realtime backend. All features (voice, embeddings, TTS)"
echo "   will use the selected provider."
echo ""
prompt realtime_backend "Realtime backend (openai/gemini)" "${cur_realtime_backend:-openai}"

openai_key=""
gemini_key=""

if [[ "$realtime_backend" == "gemini" ]]; then
  echo ""
  echo "   Gemini API key is used for voice, embeddings, and all AI features."
  prompt gemini_key "Gemini API Key (required)" "$cur_gemini_key" true
  if [[ -z "$gemini_key" ]]; then
    echo "Error: Gemini API key is required when backend is gemini."
    exit 1
  fi
else
  echo ""
  echo "   OpenAI API key is used for voice, embeddings, and all AI features."
  prompt openai_key "OpenAI API Key (required)" "$cur_openai_key" true
  if [[ -z "$openai_key" ]]; then
    echo "Error: OpenAI API key is required when backend is openai."
    exit 1
  fi
fi

# ── 2. Google Workspace account ───────────────────────────────

echo ""
echo "2. Google Workspace account — required for Meet, Calendar, and Email."
echo "   Stella needs a dedicated Workspace user. OAuth 2.0 is configured"
echo "   from the web panel after setup (Settings > Google > Connect)."

google_email=""
google_password=""
totp_secret=""

echo ""
prompt google_email "Google email" "$cur_google_email"
prompt google_password "Google password (Chrome login)" "$cur_google_password" true
prompt totp_secret "TOTP secret (2FA, optional)" "$cur_totp_secret" true

# Calendar and email are auto-enabled when OAuth is connected via the web panel.
calendar_enabled="false"
email_enabled="false"

# ── Generate RAG secrets ─────────────────────────────────────────

rag_api_key="${cur_rag_api_key:-sk-stella-$(openssl rand -hex 24)}"
db_password="${cur_db_password:-$(openssl rand -hex 16)}"

# ── Write stella.toml ────────────────────────────────────────────

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" << TOML
# ─────────────────────────────────────────────────────────────
# Stella Configuration — generated by setup.sh
# ─────────────────────────────────────────────────────────────

# ── Core credentials ──────────────────────────────────────────

[basic]
TOML

if [[ -n "$openai_key" ]]; then
  cat >> "$CONFIG_FILE" << TOML
openai_api_key = "$openai_key"
TOML
fi
if [[ -n "$gemini_key" ]]; then
  cat >> "$CONFIG_FILE" << TOML
gemini_api_key = "$gemini_key"
TOML
fi

if [[ -n "$google_email" ]]; then
  cat >> "$CONFIG_FILE" << TOML
google_email = "$google_email"
TOML
fi
if [[ -n "$google_password" ]]; then
  cat >> "$CONFIG_FILE" << TOML
google_password = "$google_password"
TOML
fi
if [[ -n "$totp_secret" ]]; then
  cat >> "$CONFIG_FILE" << TOML
totp_secret = "$totp_secret"
TOML
fi

cat >> "$CONFIG_FILE" << TOML

# ── Agent identity & behavior ─────────────────────────────────

[agent]
name = "Stella"
default_voice = "coral"
default_lang = "English"
realtime_backend = "$realtime_backend"
listen_only = false
enable_notes = true
auto_accept_guests = true

# ── Logging ───────────────────────────────────────────────────

[logs]
dir = "stella-data/logs"
rotate_time = "00:00"
retention_days = 30

# ── Chrome / CDP ──────────────────────────────────────────────

[chrome]
debug_addr = "http://127.0.0.1:18800"

# ── Calendar integration ──────────────────────────────────────
# Auto-enabled when OAuth is connected via the web panel.

[calendar]
enabled = $calendar_enabled
calendar_id = "primary"
scan_interval = 5

# ── Email scanning ────────────────────────────────────────────
# Auto-enabled when OAuth is connected via the web panel.

[email]
enabled = $email_enabled
scan_interval = 10
keywords = ["notes", "transcript", "meeting", "summary", "recording"]

# ── Owner notifications ───────────────────────────────────────

[owner]
# name = "Your Name"
# email = "you@example.com"

# ── RAG (knowledge base) ─────────────────────────────────────

[rag]
api_key = "$rag_api_key"

[rag.database]
host = "postgres"
port = 5432
name = "stella"
user = "stella"
password = "$db_password"
TOML

# ── Write docker-compose.yml ────────────────────────────────────

sed "s/__DB_PASSWORD__/$db_password/g" "$TPL_DIR/docker-compose.yml" > "$COMPOSE_FILE"

# ── Done ─────────────────────────────────────────────────────────

echo ""
echo "All set! Configuration written to stella-data/config/stella.toml"
echo ""
PUBLIC_IP=$(curl -s ifconfig.me 2>/dev/null || echo "<your-server-ip>")

echo "Next steps:"
echo "  1. docker compose run --rm stella stella web setup"
echo "  2. docker compose up --build -d"
echo "  3. Open http://${PUBLIC_IP}:5180 and go to Settings > Google to connect OAuth"
echo ""
